spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comments
    username: root
    password: Admin@000
  jpa:
    showSql: true
    hibernate:
      ddlAuto: update